### PR TITLE
Exploration4

### PR DESCRIPTION
**Pull request by Bischoff**
This is a version without monkey patching.

It breaks compatibility, and I had to redefine more methods, but I find the code much cleaner and straightforward. Also, I find it less surprising that normal ruby arrays or hashes don't shrink, but that might be a matter of tastes.

It defines two new classes, <code>Tuple</code> (elements are shrunk but not removed) and <code>Deflating</code> (elements are shrunk, or removed if unshrinkable).

Here is an usage example, meant to test a circular buffer with three primitives, <code>length()</code>, <code>put()</code> and <code>get()</code>: 
<pre>
class Rantly
  def myTestData
    Tuple.new [
      Deflating.new(
        array(integer % 8 + 1) {              # series of operations with their parameters
          Operation.new [
            ( choose :get, :put, :length ),
            integer % 65536                   # (parameters make sense only for :put)
          ]
        } ),
      integer % 10                            # size of queue
    ]
  end
end
</pre>

(<code>Operation</code> is just a convenience class above <code>Array</code> to do some nicer printing)

So you have the choice between branches <code>explore3</code> (previous patch) with monkey patching or <code>explore4</code> without. I prefer <code>explore4</code> but, again, it might be a matter of tastes.

### CODE REVIEW

**Comment by Bischoff** [comment]
Or we could do exactly the opposite: do everything with monkey patching, no new classes. We would store the way to shrink in a new member data of arrays and hashes, <code>@shrinkmode</code>.

Or you could decide to postpone the decision about the way to shrink, and just keep the new exploration algorithm. If that is what you want, I can prepare a minimal pull request with only the new exploration algorithm.

**Comment by abargnesi** [comment]
Great work! I'm in favor of `Tuple` and `Deflating` because of the explicit naming. It conveys the intent of the data structure to the reader.

What if `shrinkify`'s method signature allowed *depth* as the third argument and provide a default value (e.g. 1)? Something like:

```ruby
def shrinkify(assertion, data, depth=1)
```

Existing code wouldn't break, but furthermore would work the same. Right?

**Comment by Bischoff** [comment]
Sorry, you lost me :-) . What would be the purpose of this ''depth'' parameter?

Currently it works without it (no matter whether we use classes, monkey patching, or both).

**Comment by abargnesi** [comment]
I will take a look post-merge (likely Thursday night).

Exploration4 looks good, but could you include some tests that would be appropriate for the new shrinkify behavior as well as Deflating/Tuple data structures. These can serve as an example as well.

It may be valuable to add an *examples* directory at the top-level with some Rantly code examples.

**Pull request merged**
